// Client-side API service to communicate with server-side database operations

export class ClientDatabaseService {
  
  // User Profile Operations
  static async createUserProfile(data: {
    userId: string;
    fullName: string;
    age: number;
    gender: string;
    location: string;
    currentEducation: string;
    currentClass: string;
    previousAcademicPerformance?: string;
    currentSubjects: string[];
    careerInterests: string[];
    preferredStudyMode: string;
    academicGoals: string;
    strengths: string[];
    challenges: string[];
    parentOccupation?: string;
    familyIncome?: string;
  }) {
    console.log('ClientDatabaseService: Creating user profile with data:', data);
    
    const response = await fetch('/api/user-profile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });

    console.log('ClientDatabaseService: API response status:', response.status);

    if (!response.ok) {
      const errorData = await response.json();
      console.error('ClientDatabaseService: API error response:', errorData);
      throw new Error(errorData.error || `HTTP ${response.status}: Failed to create user profile`);
    }

    const result = await response.json();
    console.log('ClientDatabaseService: User profile created successfully');
    return result.userProfile;
  }

  static async getUserProfile(userId: string) {
    const response = await fetch(`/api/user-profile?userId=${encodeURIComponent(userId)}`);

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to fetch user profile');
    }

    const result = await response.json();
    return result.userProfile;
  }

  // Quiz Results Operations
  static async saveQuizResult(data: {
    userId: string;
    quizType: string;
    score: number;
    totalQuestions: number;
    answers: Record<string, any>;
    recommendations?: string[];
  }) {
    const response = await fetch('/api/quiz-results', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to save quiz result');
    }

    const result = await response.json();
    return result.quizResult;
  }

  static async getQuizResults(userId: string) {
    const response = await fetch(`/api/quiz-results?userId=${encodeURIComponent(userId)}`);

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to fetch quiz results');
    }

    const result = await response.json();
    return result.quizResults;
  }

  // User Settings Operations
  static async saveUserSettings(userId: string, settings: Record<string, any>) {
    const response = await fetch('/api/user-settings', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ userId, settings }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to save user settings');
    }

    const result = await response.json();
    return result.userSettings;
  }

  static async getUserSettings(userId: string) {
    const response = await fetch(`/api/user-settings?userId=${encodeURIComponent(userId)}`);

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to fetch user settings');
    }

    const result = await response.json();
    return result.userSettings;
  }

  // AI Recommendations Operations
  static async saveAIRecommendations(userId: string, recommendations: Array<{
    category: string;
    title: string;
    description: string;
    reason: string;
    priority: string;
    actionUrl?: string;
    details: string[];
  }>) {
    const response = await fetch('/api/ai-recommendations', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ userId, recommendations }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to save AI recommendations');
    }

    const result = await response.json();
    return result.aiRecommendation;
  }

  static async saveAIRecommendation(data: {
    userId: string;
    type: string;
    recommendation: Record<string, any>;
    confidence?: number;
    metadata?: Record<string, any>;
  }) {
    // Convert single recommendation to array format for the new API
    const recommendations = [{
      category: data.type,
      title: data.recommendation.title || 'AI Recommendation',
      description: data.recommendation.description || '',
      reason: data.recommendation.reason || 'Generated by AI',
      priority: 'medium',
      actionUrl: data.recommendation.actionUrl,
      details: data.recommendation.details || []
    }];
    
    return this.saveAIRecommendations(data.userId, recommendations);
  }

  static async getAIRecommendations(userId: string) {
    const response = await fetch(`/api/ai-recommendations?userId=${encodeURIComponent(userId)}`);

    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || 'Failed to fetch AI recommendations');
    }

    const result = await response.json();
    return result.recommendations;
  }

  // Utility methods for backward compatibility
  static async migrateLocalStorageToDatabase(userId: string) {
    try {
      // Check if user already has data in database
      const existingProfile = await this.getUserProfile(userId);
      if (existingProfile) {
        console.log('User profile already exists in database');
        return { success: true, message: 'Data already exists in database' };
      }

      // Get data from localStorage
      const localData = this.getLocalStorageData();
      if (Object.keys(localData).length === 0) {
        return { success: true, message: 'No local data to migrate' };
      }

      // Migrate each data type
      const migrationResults = {
        userProfile: null as any,
        quizResults: [] as any[],
        settings: null as any,
        recommendations: [] as any[]
      };

      // Migrate user profile if exists
      if (localData.userProfile) {
        try {
          migrationResults.userProfile = await this.createUserProfile({
            userId,
            ...localData.userProfile
          });
        } catch (error) {
          console.error('Failed to migrate user profile:', error);
        }
      }

      // Migrate quiz results
      if (localData.quizResults && Array.isArray(localData.quizResults)) {
        for (const quiz of localData.quizResults) {
          try {
            const result = await this.saveQuizResult({
              userId,
              ...quiz
            });
            migrationResults.quizResults.push(result);
          } catch (error) {
            console.error('Failed to migrate quiz result:', error);
          }
        }
      }

      // Migrate user settings
      if (localData.settings) {
        try {
          migrationResults.settings = await this.saveUserSettings(userId, localData.settings);
        } catch (error) {
          console.error('Failed to migrate user settings:', error);
        }
      }

      // Clear localStorage after successful migration
      this.clearLocalStorageData();

      return {
        success: true,
        message: 'Migration completed successfully',
        data: migrationResults
      };

    } catch (error) {
      console.error('Migration failed:', error);
      return {
        success: false,
        message: 'Migration failed',
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  private static getLocalStorageData() {
    if (typeof window === 'undefined') return {};

    const data: Record<string, any> = {};
    
    // Get all localStorage items that might be app-related
    const keys = ['userProfile', 'quizResults', 'userSettings', 'aiRecommendations'];
    
    for (const key of keys) {
      try {
        const item = localStorage.getItem(key);
        if (item) {
          data[key] = JSON.parse(item);
        }
      } catch (error) {
        console.error(`Failed to parse localStorage item ${key}:`, error);
      }
    }

    return data;
  }

  private static clearLocalStorageData() {
    if (typeof window === 'undefined') return;

    const keys = ['userProfile', 'quizResults', 'userSettings', 'aiRecommendations'];
    
    for (const key of keys) {
      try {
        localStorage.removeItem(key);
      } catch (error) {
        console.error(`Failed to clear localStorage item ${key}:`, error);
      }
    }
  }
}

// Export for backward compatibility
export const DatabaseService = ClientDatabaseService;