import LoginButton from "@/components/loginbutton";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Login from "@/components/login";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ position: 'fixed', top: '1.5rem', right: '2rem', zIndex: 50 }}>
          <LoginButton />
        </div>
        {children}
      </body>
    </html>
  );
}
